### ISSUE TITLE
Quickstart guide

### ISSUE THREAD

**Issue by ricjhill** [dvelasquez/carbon-tools#8]
This looks interesting  how do I  deploy it locally

**Comment by dvelasquez** [comment]
Hey @ricjhill thanks for taking the time to open an issue.

Currently this is a javascript project, and it works as a monorepo/multipackage.

If you want to use this as a dependency in your projects, you can install the finished libraries by using:

- `yarn add bytes-to-co2` or `npm i bytes-to-co2`
- `yarn add co2-data` or `npm i co2-data`

The lighthouse-co2-plugin and the co2-extension is still under development. They technically work, but have a lot of rough edges.

I'm [updating the README.md.](https://github.com/dvelasquez/carbon-tools/tree/docs/readme) Let me know if it answer your question.

**Comment by dvelasquez** [comment]
Hey, thanks @ricjhill  for getting back so quickly!

I think the issue here is that all the code was created using NodeJS v12 and since v14 the unhandled rejections are marked as errors.

For now you can switch to NodeJS in the meanwhile, if you want to develop on top of this.

You should not have this problem if you import the libraries from NPM though.

I will try to manage this issues in a separate PR.

**Comment by ricjhill** [comment]
Cheers.

**Comment by dvelasquez** [comment]
Hey @ricjhill if you have time, could to try to run this branch` feat/compat-node-v15` in your machine?

I updated the compatibility with Node v15, and it should be working (at least on my local machine and github actions).

**Comment by ricjhill** [comment]
I dont see that  branch   feat/compat-node-v15

```
$cd carbon-tools
$git  pull
$git branch
* main
```
 GIT  log shows the  last  commit  was   acdb16ef6a1275d7b32913289499ab290bab2b0d.    Could you try and push it again please.

**Comment by dvelasquez** [comment]
The changes are already in the `main` branch.

GitHub actions is also using node 15.
